### ISSUE TITLE
Example using send command?

### ISSUE THREAD

**Issue by forresti** [checkymander/Carbuncle#2]
Thanks for creating Carbuncle; I have found it to be quite helpful.

The README.md explains how to use most of the commands, but it doesn't really explain the `send` command. I tried using it in the following ways:

` .\Carbuncle.exe send /recipients "person@place.com" /subject "hello" /body "from carbuncle"`

` .\Carbuncle.exe send recipients "person@place.com" subject "hello" body "from carbuncle"`

But, on both of these, the output I got on the command line was:
```
[+] Sending an e-mail.
Recipients:
Subject:
Body:
There must be at least one name or contact group in the To, Cc, or Bcc box.
Done.
```

Would you be willing to provide an example of the correct syntax for using the `send` command?

**Comment by checkymander** [comment]
Sorry, I forgot to include that when I updated the help text.

```
carbuncle.exe send /subject:"test e-mail please ignore" /recipients:"email1@domain.com,email2@domain.com" /body:"Hello World"
```

**Comment by forresti** [comment]
Thanks! That worked perfectly!
