### ISSUE TITLE
Some commands close Outlook UI

### ISSUE THREAD

**Issue by forresti** [checkymander/Carbuncle#3]
I noticed that commands such as `searchmail` and `read` close the Outlook user-interface window when they finish running. I think this is because these commands call `MailSearcher.GetInboxItems()`. And, `MailSearcher.GetInboxItems()` calls `outlookApplication.Quit()`.

I found that removing `outlookApplication.Quit()` from `MailSearcher.GetInboxItems()` solves the issue, at least on my computer (Windows 10, Outlook 2019). Specifically, with `Quit()` removed, I find that...
* If Outlook UI is open when I start Carbuncle, the Outlook UI stays open after Carbuncle finishes.
* If Outlook UI is closed when I start Carbuncle, the Outlook UI stays closed after Carbuncle finishes.

So, I was wondering if this `Quit()` needs to be there, or if maybe we should remove it.

**Comment by checkymander** [comment]
Good catch, that was actually something I was testing in dev that I must have accidentally pushed into main 👀 I'll remove that and push lol. #devopsfail. Appreciate your testing!

**Comment by checkymander** [comment]
Fixed in https://github.com/checkymander/Carbuncle/commit/9c56b3c17b4bb66a444517db93a2483dc9594a85
